name: Rust CI

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'solana-module/**'
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'solana-module/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: solana-module

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Set up cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: solana-module

    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.22.0'
        args: '--ignore-tests --workspace'

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: solana-module/
        flags: rust
        name: rust-coverage

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: solana-module
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/trading-bot-rust:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/trading-bot-rust:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/trading-bot-rust:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/trading-bot-rust:buildcache,mode=max 